# Generated by Django 3.0.4 on 2020-04-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_to_actions', models.TextField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.', max_length=1024, verbose_name='Call to Actions payload')),
                ('page_id', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Page ID')),
            ],
        ),
    ]
