# Generated by Django 3.0.4 on 2020-04-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistent_menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentmenu',
            name='locale',
            field=models.CharField(choices=[('default', 'Default'), ('en_US', 'US'), ('vi_VN', 'Vietnam')], db_index=True, default='default', max_length=50, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='persistentmenu',
            name='call_to_actions',
            field=models.TextField(help_text="Please use the following format:</br>[{</br>&nbsp;&nbsp;'title': 'Talk to an agent',</br>&nbsp;&nbsp;'type': 'postback',</br>&nbsp;&nbsp;'payload': 'CARE_HELP',</br>},</br>{</br>&nbsp;&nbsp;'title': 'Outfit suggestions',</br>&nbsp;&nbsp;'type': 'postback',</br>&nbsp;&nbsp;'payload': 'CURATION',</br>},</br>{</br>&nbsp;&nbsp;'title': 'Shop now',</br>&nbsp;&nbsp;'type': 'web_url',</br>&nbsp;&nbsp;'url': 'https://www.facebook.com/vihu96',</br>&nbsp;&nbsp;'webview_height_ratio': 'full',</br>}]", max_length=1024, verbose_name='Call to Actions payload'),
        ),
    ]
