# Generated by Django 3.0.4 on 2020-04-03 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persistent_menu', '0002_auto_20200403_0033'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='persistentmenu',
            unique_together={('locale', 'page_id')},
        ),
    ]
