# Generated by Django 3.0.4 on 2020-03-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='Message')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('thumbnail', models.CharField(blank=True, max_length=500, verbose_name='Link thumbnail')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Post Title')),
                ('sapo', models.CharField(blank=True, max_length=500, verbose_name='Post sapo')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Link')),
                ('type', models.CharField(choices=[('TEXT', 'Nội dung'), ('UPDATE', 'Cập nhật số lượng ca VN'), ('SHARE', 'Chia sẻ Liên kết')], default='TEXT', max_length=20, verbose_name='Post type messenger')),
                ('pushAdmin', models.BooleanField(default=False, help_text='Push message to admin', verbose_name='Push Admin')),
                ('publish', models.BooleanField(default=False, help_text='Broadcast message', verbose_name='Publish')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
