# Generated by Django 3.0.4 on 2020-03-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='numline',
            field=models.IntegerField(default=3, verbose_name='Content numline'),
        ),
    ]
