# Generated by Django 3.0.5 on 2020-04-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200413_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='numline',
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Nội dung'), ('SHARE', 'Chia sẻ Thông tin')], default='TEXT', max_length=20, verbose_name='Post type messenger'),
        ),
    ]
