# Generated by Django 2.2.1 on 2020-04-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='User ID')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('access_token', models.CharField(max_length=255, verbose_name='Access Token')),
                ('expiresIn', models.DateTimeField(verbose_name='Expires In')),
            ],
        ),
    ]
