# Generated by Django 3.0.4 on 2020-04-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanpage', '0001_initial'),
        ('client', '0002_client_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='pages',
            field=models.ManyToManyField(blank=True, to='fanpage.Fanpage'),
        ),
    ]
