version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
    - db-data:/var/lib/postgresql/data

  covid-bot:
    build: .
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db-data:
