version: '3'

services:
  covid-bot:
    build: .
    restart: always
    volumes:
      - .:/code
    ports:
      - "8090:8000"
    depends_on:
      - db
      - redis
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine

volumes:
  db-data:
