# Generated by Django 3.0.4 on 2020-04-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GetStartedButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.CharField(max_length=512, verbose_name='Get Started Payload')),
                ('page_id', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Page ID')),
            ],
        ),
    ]
