# Generated by Django 3.0.4 on 2020-04-04 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=2, unique=True, verbose_name='Country Code')),
                ('name', models.CharField(max_length=255, verbose_name='Country Name')),
                ('cases', models.IntegerField(default=0, verbose_name='Total cases')),
                ('death', models.IntegerField(default=0, verbose_name='Total death')),
                ('recovered', models.IntegerField(default=0, verbose_name='Total recovered')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_index=True, verbose_name='Date')),
                ('cases', models.IntegerField(default=0, verbose_name='Cases')),
                ('death', models.IntegerField(default=0, verbose_name='Death')),
                ('recovered', models.IntegerField(default=0, verbose_name='Recovered')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='countries.Country')),
            ],
            options={
                'unique_together': {('country', 'date')},
            },
        ),
    ]
