# Generated by Django 3.0.4 on 2020-04-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fanpage',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Page ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Page Name')),
                ('access_token', models.CharField(max_length=255, verbose_name='Access Token')),
            ],
        ),
    ]
