# Generated by Django 3.0.4 on 2020-04-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=160, verbose_name='Welcome message')),
                ('locale', models.CharField(choices=[('default', 'Default'), ('en_US', 'US'), ('vi_VN', 'Vietnam')], db_index=True, max_length=50, verbose_name='Locale')),
                ('page_id', models.CharField(db_index=True, max_length=20, verbose_name='Page ID')),
            ],
        ),
    ]
