# Generated by Django 3.0.4 on 2020-04-05 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fanpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetStartedButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.CharField(max_length=512, verbose_name='Get Started Payload')),
                ('fanpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fanpage.Fanpage')),
            ],
        ),
        migrations.CreateModel(
            name='PersistentMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_to_actions', models.TextField(help_text="Please use the following format:</br>[{</br>&nbsp;&nbsp;'title': 'Talk to an agent',</br>&nbsp;&nbsp;'type': 'postback',</br>&nbsp;&nbsp;'payload': 'CARE_HELP',</br>},</br>{</br>&nbsp;&nbsp;'title': 'Outfit suggestions',</br>&nbsp;&nbsp;'type': 'postback',</br>&nbsp;&nbsp;'payload': 'CURATION',</br>},</br>{</br>&nbsp;&nbsp;'title': 'Shop now',</br>&nbsp;&nbsp;'type': 'web_url',</br>&nbsp;&nbsp;'url': 'https://www.facebook.com/vihu96',</br>&nbsp;&nbsp;'webview_height_ratio': 'full',</br>}]", max_length=1024, verbose_name='Call to Actions payload')),
                ('locale', models.CharField(choices=[('default', 'Default'), ('en_US', 'US'), ('vi_VN', 'Vietnam')], db_index=True, default='default', max_length=50, verbose_name='Locale')),
                ('fanpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fanpage.Fanpage')),
            ],
            options={
                'unique_together': {('locale', 'fanpage')},
            },
        ),
        migrations.CreateModel(
            name='GreetingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('default', 'Default'), ('en_US', 'US'), ('vi_VN', 'Vietnam')], db_index=True, max_length=50, verbose_name='Locale')),
                ('text', models.CharField(max_length=160, verbose_name='Greeting message')),
                ('fanpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fanpage.Fanpage')),
            ],
            options={
                'unique_together': {('locale', 'fanpage')},
            },
        ),
    ]
