# Generated by Django 3.0.4 on 2020-04-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255, verbose_name='Display name')),
                ('recipient_id', models.CharField(db_index=True, max_length=50, verbose_name='Recipient ID')),
                ('message_id', models.CharField(db_index=True, max_length=255, verbose_name='Message ID')),
                ('page_id', models.CharField(db_index=True, max_length=50, verbose_name='Page ID')),
                ('uid', models.CharField(db_index=True, max_length=50, verbose_name='Facebook UID')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
