# Generated by Django 3.0.4 on 2020-04-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_subscriber_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Display name'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='message_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Message ID'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='uid',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Facebook UID'),
        ),
    ]
