# Generated by Django 3.0.5 on 2020-04-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_auto_20200405_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='one_time_token',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='One time TOKEN'),
        ),
    ]
