# Generated by Django 3.0.4 on 2020-04-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Patient Code')),
                ('is_healthy', models.BooleanField(default=False, verbose_name='Patient is healthy?')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('', 'Not defined')], default='', max_length=20, verbose_name='Gender')),
                ('year_of_birth', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year of birth')),
                ('address', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Address')),
                ('detail', models.TextField(blank=True, verbose_name='Detail')),
            ],
        ),
    ]
