# Generated by Django 3.0.4 on 2020-04-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20200402_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Patient Code'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='detail',
            field=models.TextField(blank=True, verbose_name='Detail'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='year_of_birth',
            field=models.PositiveIntegerField(blank=True, max_length=4, verbose_name='Year of birth'),
        ),
    ]
