# Generated by Django 3.0.4 on 2020-04-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20200402_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='year_of_birth',
            field=models.PositiveIntegerField(blank=True, max_length=4, null=True, verbose_name='Year of birth'),
        ),
    ]
