# Generated by Django 3.0.4 on 2020-04-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20200402_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='year_of_birth',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Year of birth'),
        ),
    ]
